language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

install: wget https://raw.githubusercontent.com/atom/ci/master/build-package.sh
script: sh build-package.sh
